local colors = require("flexoki").colors
return {
    normal = {
        a = { bg = colors.blue3, fg = colors.tx },
        b = { bg = colors.ui, fg = colors.tx },
        c = { bg = colors.ui, fg = colors.tx },
        x = { bg = colors.ui, fg = colors.tx },
        y = { bg = colors.ui, fg = colors.tx },
        z = { bg = colors.ui, fg = colors.tx },
    },
    insert = {
        a = { bg = colors.green3, fg = colors.tx },
        b = { bg = colors.ui, fg = colors.tx },
        c = { bg = colors.ui, fg = colors.tx },
        x = { bg = colors.ui, fg = colors.tx },
        y = { bg = colors.ui, fg = colors.tx },
        z = { bg = colors.ui, fg = colors.tx },
    },
    visual = {
        a = { bg = colors.magenta3, fg = colors.tx },
        b = { bg = colors.ui, fg = colors.tx },
        c = { bg = colors.ui, fg = colors.tx },
        x = { bg = colors.ui, fg = colors.tx },
        y = { bg = colors.ui, fg = colors.tx },
        z = { bg = colors.ui, fg = colors.tx },
    },
    replace = {
        a = { bg = colors.red3, fg = colors.tx },
        b = { bg = colors.ui, fg = colors.tx },
        c = { bg = colors.ui, fg = colors.tx },
        x = { bg = colors.ui, fg = colors.tx },
        y = { bg = colors.ui, fg = colors.tx },
        z = { bg = colors.ui, fg = colors.tx },
    },
    command = {
        a = { bg = colors.orange3, fg = colors.tx },
        b = { bg = colors.ui, fg = colors.tx },
        c = { bg = colors.ui, fg = colors.tx },
        x = { bg = colors.ui, fg = colors.tx },
        y = { bg = colors.ui, fg = colors.tx },
        z = { bg = colors.ui, fg = colors.tx },
    },
    terminal = {
        a = { bg = colors.green3, fg = colors.tx },
        b = { bg = colors.ui, fg = colors.tx },
        c = { bg = colors.ui, fg = colors.tx },
        x = { bg = colors.ui, fg = colors.tx },
        y = { bg = colors.ui, fg = colors.tx },
        z = { bg = colors.ui, fg = colors.tx },
    },
    inactive = {
        a = { bg = colors.bg, fg = colors.tx3 },
        b = { bg = colors.bg, fg = colors.tx3 },
        c = { bg = colors.bg, fg = colors.tx3 },
        x = { bg = colors.bg, fg = colors.tx3 },
        y = { bg = colors.bg, fg = colors.tx3 },
        z = { bg = colors.bg, fg = colors.tx3 },
    },
}
