local colors = require("flexoki").colors
return {
    normal = {
        a = { bg = colors.blue4, fg = colors.blue2 },
        b = { bg = colors.bg, fg = colors.tx2 },
        c = { bg = colors.bg, fg = colors.tx2 },
        x = { bg = colors.bg, fg = colors.tx2 },
        y = { bg = colors.bg, fg = colors.tx2 },
        z = { bg = colors.bg, fg = colors.tx2 },
    },
    insert = {
        a = { bg = colors.green4, fg = colors.green },
        b = { bg = colors.bg, fg = colors.tx2 },
        c = { bg = colors.bg, fg = colors.tx2 },
        x = { bg = colors.bg, fg = colors.tx2 },
        y = { bg = colors.bg, fg = colors.tx2 },
        z = { bg = colors.bg, fg = colors.tx2 },
    },
    visual = {
        a = { bg = colors.magenta4, fg = colors.magenta },
        b = { bg = colors.bg, fg = colors.tx2 },
        c = { bg = colors.bg, fg = colors.tx2 },
        x = { bg = colors.bg, fg = colors.tx2 },
        y = { bg = colors.bg, fg = colors.tx2 },
        z = { bg = colors.bg, fg = colors.tx2 },
    },
    replace = {
        a = { bg = colors.red4, fg = colors.red },
        b = { bg = colors.bg, fg = colors.tx2 },
        c = { bg = colors.bg, fg = colors.tx2 },
        x = { bg = colors.bg, fg = colors.tx2 },
        y = { bg = colors.bg, fg = colors.tx2 },
        z = { bg = colors.bg, fg = colors.tx2 },
    },
    command = {
        a = { bg = colors.orange4, fg = colors.orange },
        b = { bg = colors.bg, fg = colors.tx2 },
        c = { bg = colors.bg, fg = colors.tx2 },
        x = { bg = colors.bg, fg = colors.tx2 },
        y = { bg = colors.bg, fg = colors.tx2 },
        z = { bg = colors.bg, fg = colors.tx2 },
    },
    terminal = {
        a = { bg = colors.green4, fg = colors.green },
        b = { bg = colors.bg, fg = colors.tx2 },
        c = { bg = colors.bg, fg = colors.tx2 },
        x = { bg = colors.bg, fg = colors.tx2 },
        y = { bg = colors.bg, fg = colors.tx2 },
        z = { bg = colors.bg, fg = colors.tx2 },
    },
    inactive = {
        a = { bg = colors.bg, fg = colors.tx3 },
        b = { bg = colors.bg, fg = colors.tx3 },
        c = { bg = colors.bg, fg = colors.tx3 },
        x = { bg = colors.bg, fg = colors.tx3 },
        y = { bg = colors.bg, fg = colors.tx3 },
        z = { bg = colors.bg, fg = colors.tx3 },
    },
}
